Pendulum_1-added
NoMonsters/studentsFCS pull request #6
Opened 2024-11-19 21:37 UTC by PetrFD

Сделал первый маятник (не затухающий), оформил в виде сабсистемы, переменные берутся из workspace

2024-11-20 14:57 UTC, NoMonsters requested changes
Привет. Да модель работает. Есть несколько замечаний.

1. Integrator, Second-Order - редко используется. Обычно строят через последовательность обычных блоков Integrator. Сдейлай через них
2. В качестве упражнения сконфигурируй модель на использование метода интегрирования с потсоянным шагом (0.01 секунда)
После этого переходи к маятнику с затуханием.

2024-11-20 21:52 UTC, PetrFD commented on Models/training/train_model_PetrFD.slx
1) Заменил Integrator, Second-Order на два обычных интегратора.
2) Настроил фиксированный шаг интегрирования в Solver равный 0.01

2024-11-27 07:59 UTC, NoMonsters requested changes
Привет.
Модели работают, но они плохо читаемы.
- На верхнем уровне какие-то 2 сабсистемы, не понтяно что их этого что. Нужно подписать: одна с затуханием другая без
- В модели с затуханием тоже спагети. Модели читаем слева направо, соответственно все повороты в обратную сторону, а тем более ты повернул входы сверху вниз - нечитаемо. Нужно что-то с минимумом пересечений и изломов. И подписать сигналы необходимые для понимания модели.

2024-11-27 08:00 UTC, NoMonsters commented
Пример читаемой модели 
![изображение](https://github.com/user-attachments/assets/67104f34-ee62-4597-8923-3d0c954d8cc8)

2024-11-27 08:04 UTC, NoMonsters commented
Ещё нужно дополнить инициализационным скриптом. В модели есть переменные g и l, они никак не инитятся и я как юзер, который просто открыл модель и хочу ей воспользоваться не понимаю что мне делать и откуда взять.
Поправь это тоже, пожалуйста и дальше наверное перейдем уже к микроконтроллерам.

2024-12-10 12:33 UTC, NoMonsters approved these changes

2024-12-10 12:38 UTC, merged